title: "Welcome to my Research Log"
description: "Documenting my experiments and my self-learning journey. A forthcoming section will be added where I will present my reflection pieces discussing my research findings from broad conceptual and philosophical perspectives."
theme: minima

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - research.md
  - log.md
  #- about.md

