title: "Welcome to my Website"
description: "A record of my independent research practice and my ongoing self-learning journey. A new section will be added where I will share my reflection pieces expanding on the wider conceptual ( and philosophical) implications of my findings."
theme: minima

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - research.md
  - log.md
  #- about.md

